// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: auth_internal_api.proto

package auth_internal_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthInternalApiClient is the client API for AuthInternalApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthInternalApiClient interface {
	ServiceRegister(ctx context.Context, in *ServiceRegisterRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ServiceLogin(ctx context.Context, in *ServiceLoginRequest, opts ...grpc.CallOption) (*JwtResponse, error)
	ServiceRefresh(ctx context.Context, in *ServiceRefreshRequest, opts ...grpc.CallOption) (*JwtResponse, error)
}

type authInternalApiClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthInternalApiClient(cc grpc.ClientConnInterface) AuthInternalApiClient {
	return &authInternalApiClient{cc}
}

func (c *authInternalApiClient) ServiceRegister(ctx context.Context, in *ServiceRegisterRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/auth_internal_api.AuthInternalApi/ServiceRegister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authInternalApiClient) ServiceLogin(ctx context.Context, in *ServiceLoginRequest, opts ...grpc.CallOption) (*JwtResponse, error) {
	out := new(JwtResponse)
	err := c.cc.Invoke(ctx, "/auth_internal_api.AuthInternalApi/ServiceLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authInternalApiClient) ServiceRefresh(ctx context.Context, in *ServiceRefreshRequest, opts ...grpc.CallOption) (*JwtResponse, error) {
	out := new(JwtResponse)
	err := c.cc.Invoke(ctx, "/auth_internal_api.AuthInternalApi/ServiceRefresh", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthInternalApiServer is the server API for AuthInternalApi service.
// All implementations must embed UnimplementedAuthInternalApiServer
// for forward compatibility
type AuthInternalApiServer interface {
	ServiceRegister(context.Context, *ServiceRegisterRequest) (*emptypb.Empty, error)
	ServiceLogin(context.Context, *ServiceLoginRequest) (*JwtResponse, error)
	ServiceRefresh(context.Context, *ServiceRefreshRequest) (*JwtResponse, error)
	mustEmbedUnimplementedAuthInternalApiServer()
}

// UnimplementedAuthInternalApiServer must be embedded to have forward compatible implementations.
type UnimplementedAuthInternalApiServer struct {
}

func (UnimplementedAuthInternalApiServer) ServiceRegister(context.Context, *ServiceRegisterRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServiceRegister not implemented")
}
func (UnimplementedAuthInternalApiServer) ServiceLogin(context.Context, *ServiceLoginRequest) (*JwtResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServiceLogin not implemented")
}
func (UnimplementedAuthInternalApiServer) ServiceRefresh(context.Context, *ServiceRefreshRequest) (*JwtResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServiceRefresh not implemented")
}
func (UnimplementedAuthInternalApiServer) mustEmbedUnimplementedAuthInternalApiServer() {}

// UnsafeAuthInternalApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthInternalApiServer will
// result in compilation errors.
type UnsafeAuthInternalApiServer interface {
	mustEmbedUnimplementedAuthInternalApiServer()
}

func RegisterAuthInternalApiServer(s grpc.ServiceRegistrar, srv AuthInternalApiServer) {
	s.RegisterService(&AuthInternalApi_ServiceDesc, srv)
}

func _AuthInternalApi_ServiceRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthInternalApiServer).ServiceRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth_internal_api.AuthInternalApi/ServiceRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthInternalApiServer).ServiceRegister(ctx, req.(*ServiceRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthInternalApi_ServiceLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthInternalApiServer).ServiceLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth_internal_api.AuthInternalApi/ServiceLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthInternalApiServer).ServiceLogin(ctx, req.(*ServiceLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthInternalApi_ServiceRefresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthInternalApiServer).ServiceRefresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth_internal_api.AuthInternalApi/ServiceRefresh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthInternalApiServer).ServiceRefresh(ctx, req.(*ServiceRefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthInternalApi_ServiceDesc is the grpc.ServiceDesc for AuthInternalApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthInternalApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth_internal_api.AuthInternalApi",
	HandlerType: (*AuthInternalApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServiceRegister",
			Handler:    _AuthInternalApi_ServiceRegister_Handler,
		},
		{
			MethodName: "ServiceLogin",
			Handler:    _AuthInternalApi_ServiceLogin_Handler,
		},
		{
			MethodName: "ServiceRefresh",
			Handler:    _AuthInternalApi_ServiceRefresh_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth_internal_api.proto",
}
